parameters:
    snowcap_im.wrapper_class: Snowcap\ImBundle\Wrapper
    snowcap_im.manager_class: Snowcap\ImBundle\Manager

services:
    snowcap_im.wrapper:
        class: %snowcap_im.wrapper_class%
        arguments: ['\Symfony\Component\Process\Process', %snowcap_im.binary_path%, %snowcap_im.timeout%]
    snowcap_im.manager:
        class: %snowcap_im.manager_class%
        arguments: [@snowcap_im.wrapper, %kernel.root_dir%, %snowcap_im.web_path%, %snowcap_im.cache_path%, %snowcap_im.formats%]

    snowcap_im.twig:
        class: Snowcap\ImBundle\Twig\Extension\ImExtension
        arguments: [@snowcap_im.manager]
        tags:
            -  { name: twig.extension }

    snowcap_im.mogrify_subscriber:
        class: Snowcap\ImBundle\Listener\MogrifySubscriber
        arguments: [%kernel.root_dir%, @snowcap_im.manager]
        tags:
            - { name: doctrine.event_subscriber}

    snowcap_im.form_extension:
        class: Snowcap\ImBundle\Form\Extension\ImageTypeExtension
        arguments: [@snowcap_im.manager]
        tags:
            -  { name: form.type_extension, alias: snowcap_core_image }
